### ISSUE TITLE
More of a feature question.

### ISSUE THREAD

**Issue by jericogantuangco** [losnappas/Song-identifier#10]
It seems this song identifier is not able to detect music played by firefox addons. Specifically, I am playing music through an addon that plays radio stations from all over the world and it seems this addon is unable to detect the music that is played through that radio addon. 

The name of the addon is Worldwide Radio. 
You can check out the addon here: https://addons.mozilla.org/en-US/firefox/addon/worldwide-radio/?src=search.

It would be great if this song identifier would be able to detect songs from this radio addon.
Thanks.

**Comment by losnappas** [comment]
That addon plays the music from its "background page". That means there's no way for this addon to "hear" it, so that's one reason why it doesn't work. That is unfortunate, but it's also the reason that that addon can play music even when the popup is closed.

So, no luck. Addons play together pretty badly, so it is kind of expected.

Thanks for the report, anyways.

**Comment by jericogantuangco** [comment]
Oh that sucks. Well maybe if firefox would someday have the feature to let other addons talk and interface with each other that would great. Thanks for the reply. Pretty cool addon though. Cheers.
